## **Basic data exploration**

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../Data/scooter.csv')

### **Exploring the data**

In [4]:
df.columns

Index(['month', 'trip_id', 'region_id', 'vehicle_id', 'started_at', 'ended_at',
       'DURATION', 'start_location_name', 'end_location_name', 'user_id',
       'trip_ledger_id'],
      dtype='object')

In [5]:
df.dtypes

month                  object
trip_id                 int64
region_id               int64
vehicle_id              int64
started_at             object
ended_at               object
DURATION               object
start_location_name    object
end_location_name      object
user_id                 int64
trip_ledger_id          int64
dtype: object

In [6]:
df.head()

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
0,May,1613335,202,9424537,5/21/2019 18:33,5/21/2019 18:40,0:07:03,"1901 Roma Ave NE, Albuquerque, NM 87106, USA","1899 Roma Ave NE, Albuquerque, NM 87106, USA",8417864,1488546
1,May,1613639,202,9424537,5/21/2019 19:07,5/21/2019 19:12,0:04:57,"1 Domenici Center en Domenici Center, Albuquer...","1111 Stanford Dr NE, Albuquerque, NM 87106, USA",8417864,1488838
2,May,1613708,202,9424537,5/21/2019 19:13,5/21/2019 19:15,0:01:14,"1 Domenici Center en Domenici Center, Albuquer...","1 Domenici Center en Domenici Center, Albuquer...",8417864,1488851
3,May,1613867,202,9424537,5/21/2019 19:29,5/21/2019 19:36,0:06:58,"Rotunda at Science & Technology Park, 801 Univ...","725 University Blvd SE, Albuquerque, NM 87106,...",8417864,1489064
4,May,1636714,202,8926493,5/24/2019 13:38,5/24/2019 13:41,0:03:06,"401 2nd St NW, Albuquerque, NM 87102, USA","401 2nd St NW, Albuquerque, NM 87102, USA",35436274,1511212

In [7]:
# Configure DataFrame to show 500 column
# pd.set_option('display_max_columns', 500)

In [10]:
df['DURATION']

0        0:07:03
1        0:04:57
2        0:01:14
3        0:06:58
4        0:03:06
          ...
34221    0:14:00
34222    0:08:00
34223    1:53:00
34224    0:12:00
34225    1:51:00
Name: DURATION, Length: 34226, dtype: object

In [11]:
df[['trip_id','DURATION','start_location_name']]

       trip_id DURATION                                start_location_name
0      1613335  0:07:03       1901 Roma Ave NE, Albuquerque, NM 87106, USA
1      1613639  0:04:57  1 Domenici Center en Domenici Center, Albuquer...
2      1613708  0:01:14  1 Domenici Center en Domenici Center, Albuquer...
3      1613867  0:06:58  Rotunda at Science & Technology Park, 801 Univ...
4      1636714  0:03:06          401 2nd St NW, Albuquerque, NM 87102, USA
...        ...      ...                                                ...
34221  2482235  0:14:00     Central @ Broadway, Albuquerque, NM 87102, USA
34222  2482254  0:08:00     224 Central Ave SW, Albuquerque, NM 87102, USA
34223  2482257  1:53:00     105 Stanford Dr SE, Albuquerque, NM 87106, USA
34224  2482275  0:12:00   100 Broadway Blvd SE, Albuquerque, NM 87102, USA
34225  2482335  1:51:00     105 Stanford Dr SE, Albuquerque, NM 87106, USA

[34226 rows x 3 columns]

In [12]:
df.sample(5)

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
3621,May,1725262,202,1794583,5/31/2019 1:22,5/31/2019 1:41,0:18:46,"Central @ Tingley, Albuquerque, NM 87104, USA","2769 Central Ave NW, Albuquerque, NM 87104, USA",37153890,1596801
14233,June,1905934,202,4731591,6/13/2019 19:30,6/13/2019 19:51,0:21:01,"219 Central Ave SW, Albuquerque, NM 87102, USA","214 Gold Ave SW, Albuquerque, NM 87102, USA",40867873,1772490
2522,May,1706748,202,8207524,5/29/2019 13:59,5/29/2019 14:01,0:02:11,"2550 Central Ave NE, Albuquerque, NM 87106, USA","Coronado Hall, Albuquerque, NM 87106, USA",36434789,1578773
19914,June,2031827,202,8464924,6/22/2019 23:48,6/23/2019 0:26,0:38:05,"308 Central Ave SE, Albuquerque, NM 87102, USA",NaN,42256230,1896551
8892,June,1818614,202,6167553,6/6/2019 23:42,6/6/2019 23:47,0:04:29,"407 Central Ave SW, Albuquerque, NM 87102, USA","622 Central Ave NW, Albuquerque, NM 87102, USA",38794303,1687494

In [13]:
#Slice the first 10 Rows
df[:10]

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
0,May,1613335,202,9424537,5/21/2019 18:33,5/21/2019 18:40,0:07:03,"1901 Roma Ave NE, Albuquerque, NM 87106, USA","1899 Roma Ave NE, Albuquerque, NM 87106, USA",8417864,1488546
1,May,1613639,202,9424537,5/21/2019 19:07,5/21/2019 19:12,0:04:57,"1 Domenici Center en Domenici Center, Albuquer...","1111 Stanford Dr NE, Albuquerque, NM 87106, USA",8417864,1488838
2,May,1613708,202,9424537,5/21/2019 19:13,5/21/2019 19:15,0:01:14,"1 Domenici Center en Domenici Center, Albuquer...","1 Domenici Center en Domenici Center, Albuquer...",8417864,1488851
3,May,1613867,202,9424537,5/21/2019 19:29,5/21/2019 19:36,0:06:58,"Rotunda at Science & Technology Park, 801 Univ...","725 University Blvd SE, Albuquerque, NM 87106,...",8417864,1489064
4,May,1636714,202,8926493,5/24/2019 13:38,5/24/2019 13:41,0:03:06,"401 2nd St NW, Albuquerque, NM 87102, USA","401 2nd St NW, Albuquerque, NM 87102, USA",35436274,1511212
5,May,1636780,202,3902020,5/24/2019 13:52,5/24/2019 14:13,0:21:27,"520 Central Ave SW, Albuquerque, NM 87102, USA","3217 Pershing Ave SE, Albuquerque, NM 87106, USA",34352757,1511371
6,May,1636856,202,5192526,5/24/2019 14:04,5/24/2019 14:34,0:30:43,"330 Tijeras Ave NW, Albuquerque, NM 87102, USA","809 Copper Ave NW, Albuquerque, NM 87102, USA",35466666,1511483
7,May,1636912,202,3902020,5/24/2019 14:14,5/24/2019 14:15,0:01:05,"3217 Pershing Ave SE, Albuquerque, NM 87106, USA","802 Wellesley Dr SE, Albuquerque, NM 87106, USA",34352757,1511390
8,May,1637035,202,5192526,5/24/2019 14:37,5/24/2019 14:43,0:05:33,"809 Copper Ave NW, Albuquerque, NM 87102, USA","809 Copper Ave NW, Albuquerque, NM 87102, USA",35466666,1511516
9,May,1637036,202,9885684,5/24/2019 14:38,5/24/2019 15:09,0:31:54,"2901 Central Ave NE, Albuquerque, NM 87106, USA","2000 Zearing Ave NW, Albuquerque, NM 87104, USA",34352757,1511666

In [14]:
# Slice from the 10 record to the end
df[10:]

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
10,May,1637075,202,5192526,5/24/2019 14:45,5/24/2019 14:48,0:03:34,"809 Copper Ave NW, Albuquerque, NM 87102, USA","809 Copper Ave NW, Albuquerque, NM 87102, USA",35466666,1511544
11,May,1637120,202,5192526,5/24/2019 14:52,5/24/2019 14:58,0:05:40,"809 Copper Ave NW, Albuquerque, NM 87102, USA","809 Copper Ave NW, Albuquerque, NM 87102, USA",35466666,1511610
12,May,1637212,202,3203954,5/24/2019 15:05,5/24/2019 15:21,0:16:37,"423 Central Ave NE, Albuquerque, NM 87102, USA","512 Central Ave SE, Albuquerque, NM 87102, USA",35490582,1511765
13,May,1637299,202,3027855,5/24/2019 15:16,5/24/2019 15:36,0:20:12,"1898 Mountain Rd NW, Albuquerque, NM 87104, USA","824 Stover Ave SW, Albuquerque, NM 87102, USA",34352757,1511876
14,May,1637378,202,4335950,5/24/2019 15:27,5/24/2019 15:31,0:03:51,"400 Marquette Ave NW, Albuquerque, NM 87102, USA","5th @ Marquette, Albuquerque, NM 87102, USA",35493806,1511834
...,...,...,...,...,...,...,...,...,...,...,...
34221,July,2482235,202,2893981,7/21/2019 23:51,7/22/2019 0:05,0:14:00,"Central @ Broadway, Albuquerque, NM 87102, USA","1418 4th St NW, Albuquerque, NM 87102, USA",42559731,2340035
34222,July,2482254,202,8201542,7/21/2019 23:52,7/22/2019 0:00,0:08:00,"224 Central Ave SW, Albuquerque, NM 87102, USA","302 San Felipe St NW, Albuquerque, NM 87104, USA",42457674,2339885
34223,July,2482257,202,5136810,7/21/2019 23:52,7/22/2019 1:45,1:53:00,"105 Stanford Dr SE, Albuquerque, NM 87106, USA","3339 Central Ave NE, Albuquerque, NM 87106, USA",42576631,2342126
34224,July,2482275,202,3125962,7/21/2019 23:53,7/22/2019 0:05,0:12:00,"100 Broadway Blvd SE, Albuquerque, NM 87102, USA","1413 4th St SW, Albuquerque, NM 87102, USA",42575656,2340036
34225,July,2482335,202,9449822,7/21/2019 23:55,7/22/2019 1:46,1:51:00,"105 Stanford Dr SE, Albuquerque, NM 87106, USA","3339 Central Ave NE, Albuquerque, NM 87106, USA",42586810,2342161

In [17]:
df.loc[34221]

month                                                            July
trip_id                                                       2482235
region_id                                                         202
vehicle_id                                                    2893981
started_at                                            7/21/2019 23:51
ended_at                                               7/22/2019 0:05
DURATION                                                      0:14:00
start_location_name    Central @ Broadway, Albuquerque, NM 87102, USA
end_location_name          1418 4th St NW, Albuquerque, NM 87102, USA
user_id                                                      42559731
trip_ledger_id                                                2340035
Name: 34221, dtype: object

In [19]:
# Select the Second elemnt in DURATION column
df.at[2, 'DURATION']

'0:01:14'

In [21]:
# Replace the record that not meet the criteria by the Nan value
df.where(df['user_id'] == 8417864)

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
0,May,1613335.0,202.0,9424537.0,5/21/2019 18:33,5/21/2019 18:40,0:07:03,"1901 Roma Ave NE, Albuquerque, NM 87106, USA","1899 Roma Ave NE, Albuquerque, NM 87106, USA",8417864.0,1488546.0
1,May,1613639.0,202.0,9424537.0,5/21/2019 19:07,5/21/2019 19:12,0:04:57,"1 Domenici Center en Domenici Center, Albuquer...","1111 Stanford Dr NE, Albuquerque, NM 87106, USA",8417864.0,1488838.0
2,May,1613708.0,202.0,9424537.0,5/21/2019 19:13,5/21/2019 19:15,0:01:14,"1 Domenici Center en Domenici Center, Albuquer...","1 Domenici Center en Domenici Center, Albuquer...",8417864.0,1488851.0
3,May,1613867.0,202.0,9424537.0,5/21/2019 19:29,5/21/2019 19:36,0:06:58,"Rotunda at Science & Technology Park, 801 Univ...","725 University Blvd SE, Albuquerque, NM 87106,...",8417864.0,1489064.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
34221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df[df['user_id'] == 8417864]

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
0,May,1613335,202,9424537,5/21/2019 18:33,5/21/2019 18:40,0:07:03,"1901 Roma Ave NE, Albuquerque, NM 87106, USA","1899 Roma Ave NE, Albuquerque, NM 87106, USA",8417864,1488546
1,May,1613639,202,9424537,5/21/2019 19:07,5/21/2019 19:12,0:04:57,"1 Domenici Center en Domenici Center, Albuquer...","1111 Stanford Dr NE, Albuquerque, NM 87106, USA",8417864,1488838
2,May,1613708,202,9424537,5/21/2019 19:13,5/21/2019 19:15,0:01:14,"1 Domenici Center en Domenici Center, Albuquer...","1 Domenici Center en Domenici Center, Albuquer...",8417864,1488851
3,May,1613867,202,9424537,5/21/2019 19:29,5/21/2019 19:36,0:06:58,"Rotunda at Science & Technology Park, 801 Univ...","725 University Blvd SE, Albuquerque, NM 87106,...",8417864,1489064
1256,May,1681624,202,8192169,5/27/2019 1:11,5/27/2019 1:11,0:00:12,"2513 Comanche Rd NE, Albuquerque, NM 87107, USA","2513 Comanche Rd NE, Albuquerque, NM 87107, USA",8417864,1554217

In [28]:
df.where((df['user_id'] == 8417864) & (df['trip_ledger_id'] == 1488838))

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,May,1613639.0,202.0,9424537.0,5/21/2019 19:07,5/21/2019 19:12,0:04:57,"1 Domenici Center en Domenici Center, Albuquer...","1111 Stanford Dr NE, Albuquerque, NM 87106, USA",8417864.0,1488838.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
34221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df[(df['user_id'] == 8417864) & (df['trip_ledger_id'] == 1488838)]

,month,trip_id,region_id,vehicle_id,started_at,ended_at,DURATION,start_location_name,end_location_name,user_id,trip_ledger_id
1,May,1613639,202,9424537,5/21/2019 19:07,5/21/2019 19:12,0:04:57,"1 Domenici Center en Domenici Center, Albuquer...","1111 Stanford Dr NE, Albuquerque, NM 87106, USA",8417864,1488838

### **Analyzing the data**

In [31]:
df.describe()

            trip_id  region_id    vehicle_id       user_id  trip_ledger_id
count  3.422600e+04    34226.0  3.422600e+04  3.422600e+04    3.422600e+04
mean   2.004438e+06      202.0  5.589507e+06  3.875420e+07    1.869549e+06
std    2.300476e+05        0.0  2.627164e+06  4.275441e+06    2.252639e+05
min    1.613335e+06      202.0  1.034847e+06  1.080200e+04    1.488546e+06
25%    1.813521e+06      202.0  3.260435e+06  3.665710e+07    1.683023e+06
50%    1.962520e+06      202.0  5.617097e+06  3.880750e+07    1.827796e+06
75%    2.182324e+06      202.0  8.012871e+06  4.222774e+07    2.042524e+06
max    2.482335e+06      202.0  9.984848e+06  4.258732e+07    2.342161e+06

In [33]:
df['start_location_name'].describe()

count                                               34220
unique                                               2972
top       1898 Mountain Rd NW, Albuquerque, NM 87104, USA
freq                                                 1210
Name: start_location_name, dtype: object

In [34]:
df['DURATION'].value_counts()

DURATION
0:04:00     825
0:03:00     807
0:05:00     728
0:06:00     649
0:07:00     627
           ...
26:04:00      1
6:14:00       1
2:30:00       1
5:00:00       1
2:39:00       1
Name: count, Length: 4135, dtype: int64

In [35]:
df['DURATION'].value_counts(normalize=True)

DURATION
0:04:00     0.025847
0:03:00     0.025284
0:05:00     0.022808
0:06:00     0.020333
0:07:00     0.019644
              ...
26:04:00    0.000031
6:14:00     0.000031
2:30:00     0.000031
5:00:00     0.000031
2:39:00     0.000031
Name: proportion, Length: 4135, dtype: float64

In [40]:
df['end_location_name'].value_counts(dropna=False)

end_location_name
NaN                                                2070
1898 Mountain Rd NW, Albuquerque, NM 87104, USA     802
Central @ Tingley, Albuquerque, NM 87104, USA       622
330 Tijeras Ave NW, Albuquerque, NM 87102, USA      529
2550 Central Ave NE, Albuquerque, NM 87106, USA     478
                                                   ...
2511 Silver Ave SE, Albuquerque, NM 87106, USA        1
323 3rd St NW, Albuquerque, NM 87102, USA             1
6500 Americas Pkwy, Albuquerque, NM 87110, USA        1
66 Hermosa Dr SE, Albuquerque, NM 87108, USA          1
3605 Campus Blvd, Albuquerque, NM 87106, USA          1
Name: count, Length: 4264, dtype: int64

In [ ]:
df['end_location_name'].value_counts(dropna=False)

end_location_name
NaN                                                2070
1898 Mountain Rd NW, Albuquerque, NM 87104, USA     802
Central @ Tingley, Albuquerque, NM 87104, USA       622
330 Tijeras Ave NW, Albuquerque, NM 87102, USA      529
2550 Central Ave NE, Albuquerque, NM 87106, USA     478
                                                   ...
2511 Silver Ave SE, Albuquerque, NM 87106, USA        1
323 3rd St NW, Albuquerque, NM 87102, USA             1
6500 Americas Pkwy, Albuquerque, NM 87110, USA        1
66 Hermosa Dr SE, Albuquerque, NM 87108, USA          1
3605 Campus Blvd, Albuquerque, NM 87106, USA          1
Name: count, Length: 4264, dtype: int64

In [41]:
df.isnull().sum()

month                     0
trip_id                   0
region_id                 0
vehicle_id                0
started_at                0
ended_at                  0
DURATION               2308
start_location_name       6
end_location_name      2070
user_id                   0
trip_ledger_id            0
dtype: int64

In [42]:
df.isna().sum()

month                     0
trip_id                   0
region_id                 0
vehicle_id                0
started_at                0
ended_at                  0
DURATION               2308
start_location_name       6
end_location_name      2070
user_id                   0
trip_ledger_id            0
dtype: int64

In [43]:
df['trip_id'].value_counts(bins=10)

(1787135.0, 1874035.0]      5561
(1700235.0, 1787135.0]      4900
(1874035.0, 1960935.0]      4316
(1960935.0, 2047835.0]      3922
(2047835.0, 2134735.0]      3296
(2221635.0, 2308535.0]      2876
(2308535.0, 2395435.0]      2515
(2134735.0, 2221635.0]      2490
(2395435.0, 2482335.0]      2228
(1612465.999, 1700235.0]    2122
Name: count, dtype: int64

## **Handling common data issues using pandas**

### **Drop rows and columns**